#!/bin/sh

# Kenneth Finnegan, 2012
# kennethfinnegan.blogspot.com

# Posts growl notifications to iOS device using prowl & curl
#
# Pass this script two (or three) arguments with the message title,
# (the message priority,) and the message.
#
# Dumps the XML response from prowl to LOG, which can be ignored
# unless you're coming anywhere close to the 1000/hr rate.

# 2012 03 08:  Initial fork from morningreport.sh
# 2012 03 21:  Replaced the hardcoded application name with `hostname`

APIKEY=$PROWL_API_KEY
LOG="/tmp/prowl.log"
touch $LOG
chmod -f 666 $LOG

# Based on if we have two or three arguments, change the default priority
if [ $# -eq "1" ]; then
     EVENT_NAME=$1
     PRIORITY="-2"
     EVENT_DESC=$1
elif [ $# -eq "2" ]; then
     echo 'parsed 2'
     EVENT_NAME=$1
     PRIORITY="-2"
     EVENT_DESC=$2
elif [ $# -eq "3" ]; then
     echo 'parsed 3'
     EVENT_NAME=$1
     PRIORITY=$2
     EVENT_DESC=$3
else
     echo "USAGE: $0 \"Event name\" \"[priority]\" \"Message body\" " \
                                                                 >/dev/fd/2
     exit
fi

# Post notification to Prowl using curl

curl -s https://api.prowlapp.com/publicapi/add \
     -F apikey="$APIKEY" \
     -F priority="$PRIORITY" \
     -F application="`hostname`" \
     -F event="$EVENT_NAME" \
     -F description="$EVENT_DESC" | tee -a /tmp/prowl.log
